---
kernel_modules:
  - br_netfilter
  - ip6_udp_tunnel
  - ip_set
  - ip_set_hash_ip
  - ip_set_hash_net
  - iptable_filter
  - iptable_mangle
  - iptable_raw
  - nf_defrag_ipv4
  - nfnetlink
  - udp_tunnel
  - veth
  - vxlan
  - x_tables
  - xt_addrtype
  - xt_comment
  - xt_mark
  - xt_multiport
  - xt_recent
  - xt_set
  - xt_statistic
  - xt_tcpudp

