---
- name: Install NTP client
  apt:
    name: ntp
    state: present
    update_cache: yes

- name: Set NTP servers based on distribution
  set_fact:
    ntp_servers: "{{ ntp_servers_debian if ansible_distribution == 'debian' else ntp_servers_ubuntu }}"

- name: Configure NTP client
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: '0644'

- name: Ensure NTP service is running and enabled
  service:
    name: ntp
    state: started
    enabled: yes
# tasks file for roles/ntp-client
